# Generated by Django 5.1.1 on 2024-10-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integrationmspconfig_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='integrationmspconfig',
            unique_together={('user', 'type')},
        ),
    ]
