# Generated by Django 5.1.1 on 2024-10-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_severity_alter_integrationmspconfig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.severity'),
        ),
    ]
